"""Exchange and symbol reference data for IBKR futures contracts.

This is a large module because it embeds the static FUTS_EXCHANGE reference
dictionary. The data is intentionally inline rather than in JSON/YAML so that
the dataclass types are enforced at import time and IDE navigation works.

Layout (search for ``# ===`` section markers):
    1. FutureSymbol dataclass            (~line 18)
    2. generateFuturesMapping()          (~line 28) — BROKEN scraper, raises NotImplementedError
    3. FUTS_EXCHANGE dict                (~line 92)  — 500+ entries, the primary API
    4. addTradingClassToTopLevel()       (~line 2985) — auto-indexes by tradingClass

Note: ``buildTickDetail()`` (scraping futuresonline.com) was removed — that site
went offline. ``FUTS_TICK_DETAIL`` / ``FutureDetail`` were also removed — runtime
tick data is now handled by ``instrumentdb`` via ``reqContractDetails`` + ``reqMarketRule``.

Public API:
    FUTS_EXCHANGE: dict[str, FutureSymbol]     — symbol/tradingClass → exchange metadata
    FutureSymbol                               — the dataclass type
    generateFuturesMapping()                   — BROKEN, raises NotImplementedError
"""
from __future__ import annotations

from dataclasses import dataclass


# === 1. FutureSymbol — exchange-level contract metadata =====================

@dataclass(slots=True, frozen=True)
class FutureSymbol:
    symbol: str
    exchange: str
    name: str
    tradingClass: str
    currency: str
    hasOptions: bool


# === 2. generateFuturesMapping — dev scraper (not called at import) =========

def generateFuturesMapping() -> dict[str, FutureSymbol]:
    """Generate mapping of:
        - future symbol => exchange, name of future
    using the IBKR margin tables (for common exchanges we want at least).

    The values should be fairly static, so we just cache a manual run as
    the global FUTS_EXCHANGE in this file."""
    raise NotImplementedError(
        "generateFuturesMapping() is broken: the IBKR margin page "
        "(index.php?f=26662) was replaced with an interactive JS wizard "
        "that pd.read_html() cannot scrape. "
        "FUTS_EXCHANGE must be maintained manually or a new data source found. "
        "See also: py_trader/futures_resolver/ for dynamic resolution via reqContractDetails."
    )
    # --- original code below kept for reference ---
    import pandas as pd

    futs = pd.read_html("https://www.interactivebrokers.com/en/index.php?f=26662")  # type: ignore
    fs: dict[str, FutureSymbol] = {}
    for ex in futs:
        for idx, row in ex.iterrows():
            # Note: we use position indexing only for the first column because the first column text
            #       _includes_ the exchange name, so it is unstable to reference by name.
            # The remaining columns all have the same names generated per section, so we reference
            # them by name for (hopefully) longer term data extraction stability.
            exchange = row.iloc[0]
            symbol = row["Underlying"]
            name = row["Product description"]
            tradingClass = row["Trading Class"]
            currency = row["Currency"]
            hasOptions = row["Has Options"]
            # fmt: off
            if exchange in {
                "CBOT", "CFE", "CME", "COMEX", "ENDEX", "EUREX",
                "GLOBEX", "ICEUS", "NYBOT", "QBALGOIUS",
                "NYSELIFFE", "NYMEX"
            }:
                # why setdefault()? Because we only want the FIRST TIME we see a symbol to generate
                # an entry here. This page as additional tables after the ones we want and we DO NOT WANT
                # the final "time at exchange" tables to pollute our previously-populated correct values.
                symboldata = FutureSymbol(symbol=symbol, exchange=exchange, name=name,
                                         tradingClass=tradingClass, currency=currency,
                                          hasOptions=hasOptions != "No")

                fs.setdefault( symbol, symboldata)

                # Addendum: for VIX symbols, we want to populate VX1 to VX52 just for completeness.
                #
                # VX[DD] are _weekly_ expirations throughout the year with the number being the week of the year.
                #
                # If the primary vix expriation is on the week number, it does not get a week number.
                # Note: this _will_ generate some invalid number entries (the 12 monthly expirations) but it's
                #       okay overall since you shouldn't be addressing them anyway.
                if tradingClass == "VX":
                    for i in range(1, 52 + 1):
                        weeklysymbol = f"VX{i:02}"

                        weeklyname = symboldata.name + f" EXPIRATION WEEK {i}"
                        # numbered weekly expirations never have options. Only the primary VX/VXM have options.
                        # vix weekly symbols are always "symbol VIX" but the trading class is the weekly symbol...
                        weeklyvix = FutureSymbol(symbol="VIX", exchange=exchange, name=weeklyname,
                                                 tradingClass=weeklysymbol, currency=currency, hasOptions=False)
                        fs[weeklysymbol] = weeklyvix

            # fmt: on

    return fs


# === 3. FUTS_EXCHANGE — primary symbol→exchange lookup (500+ entries) =======
#
# Simple mapping from name of future to exchange for future.
# Used for generating ibkr api Future Contract specification since
# each symbol must have an exchange declared.
FUTS_EXCHANGE = {
    "10Y": FutureSymbol(
        symbol="10Y",
        exchange="CBOT",
        name="10 YEAR MICRO TREASURY YIELD",
        tradingClass="10Y",
        currency="USD",
        hasOptions=False,
    ),
    "2YY": FutureSymbol(
        symbol="2YY",
        exchange="CBOT",
        name="2 YEAR MICRO TREASURY YIELD",
        tradingClass="2YY",
        currency="USD",
        hasOptions=False,
    ),
    "30Y": FutureSymbol(
        symbol="30Y",
        exchange="CBOT",
        name="30 YEAR MICRO TREASURY YIELD",
        tradingClass="30Y",
        currency="USD",
        hasOptions=False,
    ),
    "5YY": FutureSymbol(
        symbol="5YY",
        exchange="CBOT",
        name="5 YEAR MICRO TREASURY YIELD",
        tradingClass="5YY",
        currency="USD",
        hasOptions=False,
    ),
    "AIGCI": FutureSymbol(
        symbol="AIGCI",
        exchange="CBOT",
        name="BLOOMBERG COMMODITY INDEX",
        tradingClass="AW",
        currency="USD",
        hasOptions=False,
    ),
    "DHB": FutureSymbol(
        symbol="DHB",
        exchange="CBOT",
        name="BLOOMBERG U.S. CORPORATE INVESTMENT GRADE DURATION HEDGED",
        tradingClass="DHB",
        currency="USD",
        hasOptions=False,
    ),
    "AC": FutureSymbol(
        symbol="AC",
        exchange="CBOT",
        name="ETHANOL -CME",
        tradingClass="EH",
        currency="USD",
        hasOptions=False,
    ),
    "HYB": FutureSymbol(
        symbol="HYB",
        exchange="CBOT",
        name="BLOOMBERG U.S. CORPORATE HIGH YIELD VERY LIQUID",
        tradingClass="HYB",
        currency="USD",
        hasOptions=False,
    ),
    "IQB": FutureSymbol(
        symbol="IQB",
        exchange="CBOT",
        name="BLOOMBERG U.S. CORPORATE INVESTMENT GRADE",
        tradingClass="IQB",
        currency="USD",
        hasOptions=False,
    ),
    "KE": FutureSymbol(
        symbol="KE",
        exchange="CBOT",
        name="HARD RED WINTER WHEAT -KCBOT-",
        tradingClass="KE",
        currency="USD",
        hasOptions=True,
    ),
    "MTN": FutureSymbol(
        symbol="MTN",
        exchange="CBOT",
        name="MICRO ULTRA 10-YEAR U.S TREASURY NOTE",
        tradingClass="MTN",
        currency="USD",
        hasOptions=False,
    ),
    "MWN": FutureSymbol(
        symbol="MWN",
        exchange="CBOT",
        name="MICRO ULTRA US TREASURY BOND",
        tradingClass="MWN",
        currency="USD",
        hasOptions=False,
    ),
    "MYM": FutureSymbol(
        symbol="MYM",
        exchange="CBOT",
        name="MICRO E-MINI DOW JONES INDUSTRIAL AVERAGE INDEX",
        tradingClass="MYM",
        currency="USD",
        hasOptions=False,
    ),
    "MZC": FutureSymbol(
        symbol="MZC",
        exchange="CBOT",
        name="MICRO CORN FUTURES",
        tradingClass="MZC",
        currency="USD",
        hasOptions=False,
    ),
    "MZL": FutureSymbol(
        symbol="MZL",
        exchange="CBOT",
        name="MICRO SOYBEAN OIL FUTURES",
        tradingClass="MZL",
        currency="USD",
        hasOptions=False,
    ),
    "MZM": FutureSymbol(
        symbol="MZM",
        exchange="CBOT",
        name="MICRO SOYBEAN MEAL FUTURES",
        tradingClass="MZM",
        currency="USD",
        hasOptions=False,
    ),
    "MZS": FutureSymbol(
        symbol="MZS",
        exchange="CBOT",
        name="MICRO SOYBEAN FUTURES",
        tradingClass="MZS",
        currency="USD",
        hasOptions=False,
    ),
    "MZW": FutureSymbol(
        symbol="MZW",
        exchange="CBOT",
        name="MICRO WHEAT FUTURES",
        tradingClass="MZW",
        currency="USD",
        hasOptions=False,
    ),
    "DJUSRE": FutureSymbol(
        symbol="DJUSRE",
        exchange="CBOT",
        name="DOW JONES US REAL ESTATE INDEX",
        tradingClass="RX",
        currency="USD",
        hasOptions=False,
    ),
    "TN": FutureSymbol(
        symbol="TN",
        exchange="CBOT",
        name="ULTRA 10-YEAR US TREASURY NOTE",
        tradingClass="TN",
        currency="USD",
        hasOptions=False,
    ),
    "TWE": FutureSymbol(
        symbol="TWE",
        exchange="CBOT",
        name="20-YEAR U.S. TREASURY BOND",
        tradingClass="TWE",
        currency="USD",
        hasOptions=False,
    ),
    "UB": FutureSymbol(
        symbol="UB",
        exchange="CBOT",
        name="ULTRA TREASURY BOND",
        tradingClass="UB",
        currency="USD",
        hasOptions=True,
    ),
    "YC": FutureSymbol(
        symbol="YC",
        exchange="CBOT",
        name="MINI SIZED CORN FUTURES",
        tradingClass="XC",
        currency="USD",
        hasOptions=False,
    ),
    "YK": FutureSymbol(
        symbol="YK",
        exchange="CBOT",
        name="MINI SIZED SOYBEAN FUTURES",
        tradingClass="XK",
        currency="USD",
        hasOptions=False,
    ),
    "YW": FutureSymbol(
        symbol="YW",
        exchange="CBOT",
        name="MINI SIZED WHEAT FUTURES",
        tradingClass="XW",
        currency="USD",
        hasOptions=False,
    ),
    "YIA": FutureSymbol(
        symbol="YIA",
        exchange="CBOT",
        name="1-YEAR ERIS SOFR SWAP FUTURES",
        tradingClass="YIA",
        currency="USD",
        hasOptions=False,
    ),
    "YIC": FutureSymbol(
        symbol="YIC",
        exchange="CBOT",
        name="3-YEAR ERIS SOFR SWAP FUTURES",
        tradingClass="YIC",
        currency="USD",
        hasOptions=False,
    ),
    "YID": FutureSymbol(
        symbol="YID",
        exchange="CBOT",
        name="4-YEAR ERIS SOFR SWAP FUTURES",
        tradingClass="YID",
        currency="USD",
        hasOptions=False,
    ),
    "YIT": FutureSymbol(
        symbol="YIT",
        exchange="CBOT",
        name="2-YEAR ERIS SOFR SWAP FUTURES",
        tradingClass="YIT",
        currency="USD",
        hasOptions=False,
    ),
    "YIW": FutureSymbol(
        symbol="YIW",
        exchange="CBOT",
        name="5-YEAR ERIS SOFR SWAP FUTURES",
        tradingClass="YIW",
        currency="USD",
        hasOptions=False,
    ),
    "YM": FutureSymbol(
        symbol="YM",
        exchange="CBOT",
        name="E-MINI DOW JONES INDUSTRIAL AVERAGE",
        tradingClass="YM",
        currency="USD",
        hasOptions=True,
    ),
    "Z3N": FutureSymbol(
        symbol="Z3N",
        exchange="CBOT",
        name="3 YEAR US TREASURY NOTE",
        tradingClass="Z3N",
        currency="USD",
        hasOptions=False,
    ),
    "ZB": FutureSymbol(
        symbol="ZB",
        exchange="CBOT",
        name="US TREASURY BOND",
        tradingClass="ZB",
        currency="USD",
        hasOptions=True,
    ),
    "ZC": FutureSymbol(
        symbol="ZC",
        exchange="CBOT",
        name="CORN FUTURES",
        tradingClass="ZC",
        currency="USD",
        hasOptions=True,
    ),
    "ZF": FutureSymbol(
        symbol="ZF",
        exchange="CBOT",
        name="5 YEAR US TREASURY NOTE",
        tradingClass="ZF",
        currency="USD",
        hasOptions=True,
    ),
    "ZL": FutureSymbol(
        symbol="ZL",
        exchange="CBOT",
        name="SOYBEAN OIL FUTURES",
        tradingClass="ZL",
        currency="USD",
        hasOptions=True,
    ),
    "ZM": FutureSymbol(
        symbol="ZM",
        exchange="CBOT",
        name="SOYBEAN MEAL FUTURES",
        tradingClass="ZM",
        currency="USD",
        hasOptions=True,
    ),
    "ZN": FutureSymbol(
        symbol="ZN",
        exchange="CBOT",
        name="10 YEAR US TREASURY NOTE",
        tradingClass="ZN",
        currency="USD",
        hasOptions=True,
    ),
    "ZO": FutureSymbol(
        symbol="ZO",
        exchange="CBOT",
        name="OAT FUTURES",
        tradingClass="ZO",
        currency="USD",
        hasOptions=True,
    ),
    "ZQ": FutureSymbol(
        symbol="ZQ",
        exchange="CBOT",
        name="30 DAY FED FUNDS",
        tradingClass="ZQ",
        currency="USD",
        hasOptions=True,
    ),
    "ZR": FutureSymbol(
        symbol="ZR",
        exchange="CBOT",
        name="ROUGH RICE FUTURES",
        tradingClass="ZR",
        currency="USD",
        hasOptions=True,
    ),
    "ZS": FutureSymbol(
        symbol="ZS",
        exchange="CBOT",
        name="SOYBEAN FUTURES",
        tradingClass="ZS",
        currency="USD",
        hasOptions=True,
    ),
    "ZT": FutureSymbol(
        symbol="ZT",
        exchange="CBOT",
        name="2 YEAR US TREASURY NOTE",
        tradingClass="ZT",
        currency="USD",
        hasOptions=True,
    ),
    "ZW": FutureSymbol(
        symbol="ZW",
        exchange="CBOT",
        name="WHEAT FUTURES",
        tradingClass="ZW",
        currency="USD",
        hasOptions=True,
    ),
    "IBXXIBHY": FutureSymbol(
        symbol="IBXXIBHY",
        exchange="CFE",
        name="IBOXX ISHARES $ HIGH YIELD CORPORATE BOND INDEX TR",
        tradingClass="IBHY",
        currency="USD",
        hasOptions=False,
    ),
    "IBXXIBIG": FutureSymbol(
        symbol="IBXXIBIG",
        exchange="CFE",
        name="IBOXX ISHARES $ INVESTMENT GRADE CORPORATE BOND INDEX TR",
        tradingClass="IBIG",
        currency="USD",
        hasOptions=True,
    ),
    "VIX": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX",
        tradingClass="VX",
        currency="USD",
        hasOptions=True,
    ),
    "VX01": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 1",
        tradingClass="VX01",
        currency="USD",
        hasOptions=False,
    ),
    "VX02": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 2",
        tradingClass="VX02",
        currency="USD",
        hasOptions=False,
    ),
    "VX03": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 3",
        tradingClass="VX03",
        currency="USD",
        hasOptions=False,
    ),
    "VX04": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 4",
        tradingClass="VX04",
        currency="USD",
        hasOptions=False,
    ),
    "VX05": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 5",
        tradingClass="VX05",
        currency="USD",
        hasOptions=False,
    ),
    "VX06": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 6",
        tradingClass="VX06",
        currency="USD",
        hasOptions=False,
    ),
    "VX07": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 7",
        tradingClass="VX07",
        currency="USD",
        hasOptions=False,
    ),
    "VX08": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 8",
        tradingClass="VX08",
        currency="USD",
        hasOptions=False,
    ),
    "VX09": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 9",
        tradingClass="VX09",
        currency="USD",
        hasOptions=False,
    ),
    "VX10": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 10",
        tradingClass="VX10",
        currency="USD",
        hasOptions=False,
    ),
    "VX11": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 11",
        tradingClass="VX11",
        currency="USD",
        hasOptions=False,
    ),
    "VX12": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 12",
        tradingClass="VX12",
        currency="USD",
        hasOptions=False,
    ),
    "VX13": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 13",
        tradingClass="VX13",
        currency="USD",
        hasOptions=False,
    ),
    "VX14": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 14",
        tradingClass="VX14",
        currency="USD",
        hasOptions=False,
    ),
    "VX15": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 15",
        tradingClass="VX15",
        currency="USD",
        hasOptions=False,
    ),
    "VX16": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 16",
        tradingClass="VX16",
        currency="USD",
        hasOptions=False,
    ),
    "VX17": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 17",
        tradingClass="VX17",
        currency="USD",
        hasOptions=False,
    ),
    "VX18": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 18",
        tradingClass="VX18",
        currency="USD",
        hasOptions=False,
    ),
    "VX19": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 19",
        tradingClass="VX19",
        currency="USD",
        hasOptions=False,
    ),
    "VX20": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 20",
        tradingClass="VX20",
        currency="USD",
        hasOptions=False,
    ),
    "VX21": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 21",
        tradingClass="VX21",
        currency="USD",
        hasOptions=False,
    ),
    "VX22": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 22",
        tradingClass="VX22",
        currency="USD",
        hasOptions=False,
    ),
    "VX23": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 23",
        tradingClass="VX23",
        currency="USD",
        hasOptions=False,
    ),
    "VX24": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 24",
        tradingClass="VX24",
        currency="USD",
        hasOptions=False,
    ),
    "VX25": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 25",
        tradingClass="VX25",
        currency="USD",
        hasOptions=False,
    ),
    "VX26": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 26",
        tradingClass="VX26",
        currency="USD",
        hasOptions=False,
    ),
    "VX27": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 27",
        tradingClass="VX27",
        currency="USD",
        hasOptions=False,
    ),
    "VX28": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 28",
        tradingClass="VX28",
        currency="USD",
        hasOptions=False,
    ),
    "VX29": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 29",
        tradingClass="VX29",
        currency="USD",
        hasOptions=False,
    ),
    "VX30": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 30",
        tradingClass="VX30",
        currency="USD",
        hasOptions=False,
    ),
    "VX31": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 31",
        tradingClass="VX31",
        currency="USD",
        hasOptions=False,
    ),
    "VX32": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 32",
        tradingClass="VX32",
        currency="USD",
        hasOptions=False,
    ),
    "VX33": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 33",
        tradingClass="VX33",
        currency="USD",
        hasOptions=False,
    ),
    "VX34": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 34",
        tradingClass="VX34",
        currency="USD",
        hasOptions=False,
    ),
    "VX35": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 35",
        tradingClass="VX35",
        currency="USD",
        hasOptions=False,
    ),
    "VX36": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 36",
        tradingClass="VX36",
        currency="USD",
        hasOptions=False,
    ),
    "VX37": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 37",
        tradingClass="VX37",
        currency="USD",
        hasOptions=False,
    ),
    "VX38": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 38",
        tradingClass="VX38",
        currency="USD",
        hasOptions=False,
    ),
    "VX39": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 39",
        tradingClass="VX39",
        currency="USD",
        hasOptions=False,
    ),
    "VX40": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 40",
        tradingClass="VX40",
        currency="USD",
        hasOptions=False,
    ),
    "VX41": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 41",
        tradingClass="VX41",
        currency="USD",
        hasOptions=False,
    ),
    "VX42": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 42",
        tradingClass="VX42",
        currency="USD",
        hasOptions=False,
    ),
    "VX43": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 43",
        tradingClass="VX43",
        currency="USD",
        hasOptions=False,
    ),
    "VX44": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 44",
        tradingClass="VX44",
        currency="USD",
        hasOptions=False,
    ),
    "VX45": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 45",
        tradingClass="VX45",
        currency="USD",
        hasOptions=False,
    ),
    "VX46": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 46",
        tradingClass="VX46",
        currency="USD",
        hasOptions=False,
    ),
    "VX47": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 47",
        tradingClass="VX47",
        currency="USD",
        hasOptions=False,
    ),
    "VX48": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 48",
        tradingClass="VX48",
        currency="USD",
        hasOptions=False,
    ),
    "VX49": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 49",
        tradingClass="VX49",
        currency="USD",
        hasOptions=False,
    ),
    "VX50": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 50",
        tradingClass="VX50",
        currency="USD",
        hasOptions=False,
    ),
    "VX51": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 51",
        tradingClass="VX51",
        currency="USD",
        hasOptions=False,
    ),
    "VX52": FutureSymbol(
        symbol="VIX",
        exchange="CFE",
        name="CBOE VOLATILITY INDEX EXPIRATION WEEK 52",
        tradingClass="VX52",
        currency="USD",
        hasOptions=False,
    ),
    "VXM": FutureSymbol(
        symbol="VXM",
        exchange="CFE",
        name="MINI CBOE VOLATILITY INDEX FUTURES",
        tradingClass="VXM",
        currency="USD",
        hasOptions=False,
    ),
    "AUD": FutureSymbol(
        symbol="AUD",
        exchange="CME",
        name="AUSTRALIAN DOLLAR",
        tradingClass="6A",
        currency="USD",
        hasOptions=True,
    ),
    "GBP": FutureSymbol(
        symbol="GBP",
        exchange="CME",
        name="BRITISH POUND",
        tradingClass="6B",
        currency="USD",
        hasOptions=True,
    ),
    "CAD": FutureSymbol(
        symbol="CAD",
        exchange="CME",
        name="CANADIAN DOLLAR",
        tradingClass="6C",
        currency="USD",
        hasOptions=True,
    ),
    "EUR": FutureSymbol(
        symbol="EUR",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="6E",
        currency="USD",
        hasOptions=True,
    ),
    "JPY": FutureSymbol(
        symbol="JPY",
        exchange="CME",
        name="JAPANESE YEN",
        tradingClass="6J",
        currency="USD",
        hasOptions=True,
    ),
    "BRE": FutureSymbol(
        symbol="BRE",
        exchange="CME",
        name="BRAZILIAN REAL",
        tradingClass="6L",
        currency="USD",
        hasOptions=True,
    ),
    "MXP": FutureSymbol(
        symbol="MXP",
        exchange="CME",
        name="MEXICAN PESO",
        tradingClass="6M",
        currency="USD",
        hasOptions=True,
    ),
    "NZD": FutureSymbol(
        symbol="NZD",
        exchange="CME",
        name="NEW ZEALAND DOLLAR",
        tradingClass="6N",
        currency="USD",
        hasOptions=True,
    ),
    "RUR *": FutureSymbol(
        symbol="RUR *",
        exchange="CME",
        name="RUSSIAN RUBLE IN US DOLLARS",
        tradingClass="6R",
        currency="USD",
        hasOptions=True,
    ),
    "CHF": FutureSymbol(
        symbol="CHF",
        exchange="CME",
        name="SWISS FRANC",
        tradingClass="6S",
        currency="USD",
        hasOptions=True,
    ),
    "ZAR": FutureSymbol(
        symbol="ZAR",
        exchange="CME",
        name="SOUTH AFRICAN RAND",
        tradingClass="6Z",
        currency="USD",
        hasOptions=False,
    ),
    "ACDX": FutureSymbol(
        symbol="ACDX",
        exchange="CME",
        name="AUSTRALIAN DOLLAR",
        tradingClass="ACD",
        currency="CAD",
        hasOptions=False,
    ),
    "AJY": FutureSymbol(
        symbol="AJY",
        exchange="CME",
        name="AUSTRALIAN DOLLAR",
        tradingClass="AJY",
        currency="JPY",
        hasOptions=False,
    ),
    "BFF": FutureSymbol(
        symbol="BFF",
        exchange="CME",
        name="CME CF BITCOIN REFERENCE RATE NEW YORK - BFF FUTURES",
        tradingClass="BFF",
        currency="USD",
        hasOptions=False,
    ),
    "BQX": FutureSymbol(
        symbol="BQX",
        exchange="CME",
        name="CME E-MINI NASDAQ BIOTECHNOLOGY",
        tradingClass="BIO",
        currency="USD",
        hasOptions=False,
    ),
    "BOS": FutureSymbol(
        symbol="BOS",
        exchange="CME",
        name="BOSTON HOUSING INDEX",
        tradingClass="BOS",
        currency="USD",
        hasOptions=False,
    ),
    "BRR": FutureSymbol(
        symbol="BRR",
        exchange="CME",
        name="CME CF BITCOIN REFERENCE RATE",
        tradingClass="BTC",
        currency="USD",
        hasOptions=True,
    ),
    "BTCEURRR": FutureSymbol(
        symbol="BTCEURRR",
        exchange="CME",
        name="CME CF BITCOIN-EURO REFERENCE RATE",
        tradingClass="BTE",
        currency="EUR",
        hasOptions=False,
    ),
    "CB": FutureSymbol(
        symbol="CB",
        exchange="CME",
        name="CME CASH-SETTLED BUTTER FUTURES",
        tradingClass="CB",
        currency="USD",
        hasOptions=False,
    ),
    "CHI": FutureSymbol(
        symbol="CHI",
        exchange="CME",
        name="CHICAGO HOUSING INDEX",
        tradingClass="CHI",
        currency="USD",
        hasOptions=False,
    ),
    "CLP": FutureSymbol(
        symbol="CLP",
        exchange="CME",
        name="CHILEAN PESO",
        tradingClass="CHP",
        currency="USD",
        hasOptions=False,
    ),
    "CJY": FutureSymbol(
        symbol="CJY",
        exchange="CME",
        name="CANADIAN DOLLAR",
        tradingClass="CJY",
        currency="JPY",
        hasOptions=False,
    ),
    "CNH": FutureSymbol(
        symbol="CNH",
        exchange="CME",
        name="UNITED STATES DOLLAR",
        tradingClass="CNH",
        currency="CNH",
        hasOptions=False,
    ),
    "CSC": FutureSymbol(
        symbol="CSC",
        exchange="CME",
        name="CHEESE",
        tradingClass="CSC",
        currency="USD",
        hasOptions=False,
    ),
    "CUS": FutureSymbol(
        symbol="CUS",
        exchange="CME",
        name="HOUSING INDEX COMPOSITE",
        tradingClass="CUS",
        currency="USD",
        hasOptions=False,
    ),
    "CZK": FutureSymbol(
        symbol="CZK",
        exchange="CME",
        name="CZECH KORUNA",
        tradingClass="CZK",
        currency="USD",
        hasOptions=True,
    ),
    "DA": FutureSymbol(
        symbol="DA",
        exchange="CME",
        name="MILK CLASS III INDEX",
        tradingClass="DC",
        currency="USD",
        hasOptions=True,
    ),
    "DEN": FutureSymbol(
        symbol="DEN",
        exchange="CME",
        name="DENVER HOUSING INDEX",
        tradingClass="DEN",
        currency="USD",
        hasOptions=False,
    ),
    "DY": FutureSymbol(
        symbol="DY",
        exchange="CME",
        name="CME DRY WHEY INDEX",
        tradingClass="DY",
        currency="USD",
        hasOptions=False,
    ),
    "E7": FutureSymbol(
        symbol="E7",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="E7",
        currency="USD",
        hasOptions=False,
    ),
    "EAD": FutureSymbol(
        symbol="EAD",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="EAD",
        currency="AUD",
        hasOptions=False,
    ),
    "ECD": FutureSymbol(
        symbol="ECD",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="ECD",
        currency="CAD",
        hasOptions=False,
    ),
    "ECK": FutureSymbol(
        symbol="ECK",
        exchange="CME",
        name="CZECH KORUNA",
        tradingClass="ECK",
        currency="EUR",
        hasOptions=False,
    ),
    "EHF": FutureSymbol(
        symbol="EHF",
        exchange="CME",
        name="HUNGARIAN FORINT",
        tradingClass="EHF",
        currency="EUR",
        hasOptions=True,
    ),
    "EMD": FutureSymbol(
        symbol="EMD",
        exchange="CME",
        name="E-MINI S&P MIDCAP 400 FUTURES",
        tradingClass="EMD",
        currency="USD",
        hasOptions=True,
    ),
    "NIY": FutureSymbol(
        symbol="NIY",
        exchange="CME",
        name="YEN DENOMINATED NIKKEI 225 INDEX",
        tradingClass="ENY",
        currency="JPY",
        hasOptions=False,
    ),
    "EPZ": FutureSymbol(
        symbol="EPZ",
        exchange="CME",
        name="POLISH ZLOTY",
        tradingClass="EPZ",
        currency="EUR",
        hasOptions=True,
    ),
    "ES": FutureSymbol(
        symbol="ES",
        exchange="CME",
        name="E-MINI S&P 500",
        tradingClass="ES",
        currency="USD",
        hasOptions=True,
    ),
    "SPXESUP": FutureSymbol(
        symbol="SPXESUP",
        exchange="CME",
        name="E-MINI S&P 500 ESG",
        tradingClass="ESG",
        currency="USD",
        hasOptions=False,
    ),
    "ESTR": FutureSymbol(
        symbol="ESTR",
        exchange="CME",
        name="EURO SHORT-TERM RATE",
        tradingClass="ESR",
        currency="EUR",
        hasOptions=False,
    ),
    "ETHEURRR": FutureSymbol(
        symbol="ETHEURRR",
        exchange="CME",
        name="CME CF ETHER-EURO REFERENCE RATE",
        tradingClass="ETE",
        currency="EUR",
        hasOptions=False,
    ),
    "ETHUSDRR": FutureSymbol(
        symbol="ETHUSDRR",
        exchange="CME",
        name="CME CF ETHER-DOLLAR REFERENCE RATE",
        tradingClass="ETH",
        currency="USD",
        hasOptions=True,
    ),
    "GSCI": FutureSymbol(
        symbol="GSCI",
        exchange="CME",
        name="S&P-GSCI INDEX",
        tradingClass="GD",
        currency="USD",
        hasOptions=False,
    ),
    "GDK": FutureSymbol(
        symbol="GDK",
        exchange="CME",
        name="CLASS IV MILK - 200K LBS",
        tradingClass="GDK",
        currency="USD",
        hasOptions=False,
    ),
    "GF": FutureSymbol(
        symbol="GF",
        exchange="CME",
        name="FEEDER CATTLE",
        tradingClass="GF",
        currency="USD",
        hasOptions=True,
    ),
    "NF": FutureSymbol(
        symbol="NF",
        exchange="CME",
        name="NON FAT DRY MILK INDEX",
        tradingClass="GNF",
        currency="USD",
        hasOptions=False,
    ),
    "HE": FutureSymbol(
        symbol="HE",
        exchange="CME",
        name="LEAN HOGS",
        tradingClass="HE",
        currency="USD",
        hasOptions=True,
    ),
    "HUF": FutureSymbol(
        symbol="HUF",
        exchange="CME",
        name="HUNGARIAN FORINT",
        tradingClass="HUF",
        currency="USD",
        hasOptions=True,
    ),
    "IBAA": FutureSymbol(
        symbol="IBAA",
        exchange="CME",
        name="BOVESPA INDEX - USD",
        tradingClass="IBV",
        currency="USD",
        hasOptions=False,
    ),
    "ILS": FutureSymbol(
        symbol="ILS",
        exchange="CME",
        name="ISRAELI SHEKEL",
        tradingClass="ILS",
        currency="USD",
        hasOptions=True,
    ),
    "J7": FutureSymbol(
        symbol="J7",
        exchange="CME",
        name="JAPANESE YEN",
        tradingClass="J7",
        currency="USD",
        hasOptions=False,
    ),
    "KRW": FutureSymbol(
        symbol="KRW",
        exchange="CME",
        name="KOREAN WON",
        tradingClass="KRW",
        currency="USD",
        hasOptions=True,
    ),
    "LAV": FutureSymbol(
        symbol="LAV",
        exchange="CME",
        name="LAS VEGAS HOUSING INDEX",
        tradingClass="LAV",
        currency="USD",
        hasOptions=False,
    ),
    "LAX": FutureSymbol(
        symbol="LAX",
        exchange="CME",
        name="LOS ANGELES HOUSING INDEX",
        tradingClass="LAX",
        currency="USD",
        hasOptions=False,
    ),
    "LBR": FutureSymbol(
        symbol="LBR",
        exchange="CME",
        name="LUMBER FUTURES",
        tradingClass="LBR",
        currency="USD",
        hasOptions=False,
    ),
    "LE": FutureSymbol(
        symbol="LE",
        exchange="CME",
        name="LIVE CATTLE",
        tradingClass="LE",
        currency="USD",
        hasOptions=True,
    ),
    "M2K": FutureSymbol(
        symbol="M2K",
        exchange="CME",
        name="MICRO E-MINI RUSSELL 2000 INDEX",
        tradingClass="M2K",
        currency="USD",
        hasOptions=False,
    ),
    "M6A": FutureSymbol(
        symbol="M6A",
        exchange="CME",
        name="AUSTRALIAN DOLLAR",
        tradingClass="M6A",
        currency="USD",
        hasOptions=False,
    ),
    "M6B": FutureSymbol(
        symbol="M6B",
        exchange="CME",
        name="BRITISH POUND",
        tradingClass="M6B",
        currency="USD",
        hasOptions=False,
    ),
    "M6E": FutureSymbol(
        symbol="M6E",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="M6E",
        currency="USD",
        hasOptions=False,
    ),
    "MBT": FutureSymbol(
        symbol="MBT",
        exchange="CME",
        name="MICRO BITCOIN",
        tradingClass="MBT",
        currency="USD",
        hasOptions=True,
    ),
    "MCD": FutureSymbol(
        symbol="MCD",
        exchange="CME",
        name="CANADIAN DOLLAR",
        tradingClass="MCD",
        currency="USD",
        hasOptions=False,
    ),
    "MES": FutureSymbol(
        symbol="MES",
        exchange="CME",
        name="MICRO E-MINI S&P 500 STOCK PRICE INDEX",
        tradingClass="MES",
        currency="USD",
        hasOptions=True,
    ),
    "MET": FutureSymbol(
        symbol="MET",
        exchange="CME",
        name="MICRO ETHER",
        tradingClass="MET",
        currency="USD",
        hasOptions=True,
    ),
    "MIA": FutureSymbol(
        symbol="MIA",
        exchange="CME",
        name="MIAMI HOUSING INDEX",
        tradingClass="MIA",
        currency="USD",
        hasOptions=False,
    ),
    "MIR": FutureSymbol(
        symbol="MIR",
        exchange="CME",
        name="INDIAN RUPEE",
        tradingClass="MIR",
        currency="USD",
        hasOptions=False,
    ),
    "MNH": FutureSymbol(
        symbol="MNH",
        exchange="CME",
        name="UNITED STATES DOLLAR",
        tradingClass="MNH",
        currency="CNH",
        hasOptions=False,
    ),
    "MNI": FutureSymbol(
        symbol="MNI",
        exchange="CME",
        name="MICRO YEN DENOMINATED NIKKEI 225",
        tradingClass="MNI",
        currency="JPY",
        hasOptions=False,
    ),
    "MNK": FutureSymbol(
        symbol="MNK",
        exchange="CME",
        name="MICRO DOLLAR DENOMINATED NIKKEI 225",
        tradingClass="MNK",
        currency="USD",
        hasOptions=False,
    ),
    "MNQ": FutureSymbol(
        symbol="MNQ",
        exchange="CME",
        name="MICRO E-MINI NASDAQ-100 INDEX",
        tradingClass="MNQ",
        currency="USD",
        hasOptions=True,
    ),
    "MSF": FutureSymbol(
        symbol="MSF",
        exchange="CME",
        name="SWISS FRANC",
        tradingClass="MSF",
        currency="USD",
        hasOptions=False,
    ),
    "NKD": FutureSymbol(
        symbol="NKD",
        exchange="CME",
        name="DOLLAR DENOMINATED NIKKEI 225 INDEX",
        tradingClass="NKD",
        currency="USD",
        hasOptions=False,
    ),
    "NOK": FutureSymbol(
        symbol="NOK",
        exchange="CME",
        name="NORWEGIAN KRONE",
        tradingClass="NOK",
        currency="USD",
        hasOptions=False,
    ),
    "NQ": FutureSymbol(
        symbol="NQ",
        exchange="CME",
        name="E-MINI NASDAQ 100",
        tradingClass="NQ",
        currency="USD",
        hasOptions=True,
    ),
    "NYM": FutureSymbol(
        symbol="NYM",
        exchange="CME",
        name="NEW YORK HOUSING INDEX",
        tradingClass="NYM",
        currency="USD",
        hasOptions=False,
    ),
    "PJY": FutureSymbol(
        symbol="PJY",
        exchange="CME",
        name="BRITISH POUND",
        tradingClass="PJY",
        currency="JPY",
        hasOptions=False,
    ),
    "PLN": FutureSymbol(
        symbol="PLN",
        exchange="CME",
        name="POLISH ZLOTY",
        tradingClass="PLN",
        currency="USD",
        hasOptions=True,
    ),
    "PSF": FutureSymbol(
        symbol="PSF",
        exchange="CME",
        name="BRITISH POUND",
        tradingClass="PSF",
        currency="CHF",
        hasOptions=False,
    ),
    "RF": FutureSymbol(
        symbol="RF",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="RF",
        currency="CHF",
        hasOptions=False,
    ),
    "RMB": FutureSymbol(
        symbol="RMB",
        exchange="CME",
        name="CME CHINESE RENMINBI IN US DOLLAR CROSS RATE",
        tradingClass="RMB",
        currency="USD",
        hasOptions=True,
    ),
    "RME": FutureSymbol(
        symbol="RME",
        exchange="CME",
        name="CME CHINESE RENMINBI IN EURO CROSS RATE",
        tradingClass="RME",
        currency="EUR",
        hasOptions=True,
    ),
    "RP": FutureSymbol(
        symbol="RP",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="RP",
        currency="GBP",
        hasOptions=False,
    ),
    "RS1": FutureSymbol(
        symbol="RS1",
        exchange="CME",
        name="E-MINI RUSSELL 1000 INDEX FUTURES",
        tradingClass="RS1",
        currency="USD",
        hasOptions=False,
    ),
    "RSG": FutureSymbol(
        symbol="RSG",
        exchange="CME",
        name="E-MINI RUSSELL 1000 GROWTH INDEX FUTURES",
        tradingClass="RSG",
        currency="USD",
        hasOptions=False,
    ),
    "RSV": FutureSymbol(
        symbol="RSV",
        exchange="CME",
        name="E-MINI RUSSELL 1000 VALUE INDEX FUTURES",
        tradingClass="RSV",
        currency="USD",
        hasOptions=False,
    ),
    "RTY": FutureSymbol(
        symbol="RTY",
        exchange="CME",
        name="E-MINI RUSSELL 2000 INDEX",
        tradingClass="RTY",
        currency="USD",
        hasOptions=True,
    ),
    "RY": FutureSymbol(
        symbol="RY",
        exchange="CME",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="RY",
        currency="JPY",
        hasOptions=True,
    ),
    "SPXDIVAN": FutureSymbol(
        symbol="SPXDIVAN",
        exchange="CME",
        name="S&P 500 DIVIDEND POINTS (ANNUAL) INDEX",
        tradingClass="SDA",
        currency="USD",
        hasOptions=False,
    ),
    "SDG": FutureSymbol(
        symbol="SDG",
        exchange="CME",
        name="SAN DIEGO HOUSING INDEX",
        tradingClass="SDG",
        currency="USD",
        hasOptions=False,
    ),
    "SEK": FutureSymbol(
        symbol="SEK",
        exchange="CME",
        name="SWEDISH KRONA",
        tradingClass="SEK",
        currency="USD",
        hasOptions=False,
    ),
    "SFR": FutureSymbol(
        symbol="SFR",
        exchange="CME",
        name="SAN FRANCISCO HOUSING INDEX",
        tradingClass="SFR",
        currency="USD",
        hasOptions=False,
    ),
    "SGX": FutureSymbol(
        symbol="SGX",
        exchange="CME",
        name="SHORT GILT",
        tradingClass="SG",
        currency="USD",
        hasOptions=False,
    ),
    "SIR": FutureSymbol(
        symbol="SIR",
        exchange="CME",
        name="INDIAN RUPEE",
        tradingClass="SIR",
        currency="USD",
        hasOptions=False,
    ),
    "SJY": FutureSymbol(
        symbol="SJY",
        exchange="CME",
        name="SWISS FRANC",
        tradingClass="SJY",
        currency="JPY",
        hasOptions=False,
    ),
    "SMC": FutureSymbol(
        symbol="SMC",
        exchange="CME",
        name="E-MINI S&P SMALLCAP 600 FUTURES",
        tradingClass="SMC",
        currency="USD",
        hasOptions=False,
    ),
    "SONIA": FutureSymbol(
        symbol="SONIA",
        exchange="CME",
        name="STERLING OVERNIGHT INDEX AVERAGE",
        tradingClass="SON",
        currency="GBP",
        hasOptions=False,
    ),
    "SOFR1": FutureSymbol(
        symbol="SOFR1",
        exchange="CME",
        name="SECURED OVERNIGHT FINANCING RATE 1-MONTH AVERAGE OF RATES",
        tradingClass="SR1",
        currency="USD",
        hasOptions=False,
    ),
    "SOFR3": FutureSymbol(
        symbol="SOFR3",
        exchange="CME",
        name="SECURED OVERNIGHT FINANCING RATE 3-MONTH AVERAGE OF RATES",
        tradingClass="SR3",
        currency="USD",
        hasOptions=True,
    ),
    "SVX": FutureSymbol(
        symbol="SVX",
        exchange="CME",
        name="SCHNEIDER ELECTRIC SE",
        tradingClass="SU",
        currency="USD",
        hasOptions=False,
    ),
    "TBF3": FutureSymbol(
        symbol="TBF3",
        exchange="CME",
        name="13-WEEK US TREASURY BILL",
        tradingClass="TBF3",
        currency="USD",
        hasOptions=False,
    ),
    "WDC": FutureSymbol(
        symbol="WDC",
        exchange="CME",
        name="WASHINGTON DC HOUSING INDEX",
        tradingClass="WDC",
        currency="USD",
        hasOptions=False,
    ),
    "IXB": FutureSymbol(
        symbol="IXB",
        exchange="CME",
        name="MATERIALS SELECT SECTOR INDEX",
        tradingClass="XAB",
        currency="USD",
        hasOptions=False,
    ),
    "IXE": FutureSymbol(
        symbol="IXE",
        exchange="CME",
        name="ENERGY SELECT SECTOR INDEX",
        tradingClass="XAE",
        currency="USD",
        hasOptions=False,
    ),
    "SIXM": FutureSymbol(
        symbol="SIXM",
        exchange="CME",
        name="FINANCIAL SELECT SECTOR INDEX",
        tradingClass="XAF",
        currency="USD",
        hasOptions=False,
    ),
    "IXI": FutureSymbol(
        symbol="IXI",
        exchange="CME",
        name="INDUSTRIAL SELECT SECTOR INDEX",
        tradingClass="XAI",
        currency="USD",
        hasOptions=False,
    ),
    "SIXT": FutureSymbol(
        symbol="SIXT",
        exchange="CME",
        name="TECHNOLOGY SELECT SECTOR INDEX -",
        tradingClass="XAK",
        currency="USD",
        hasOptions=False,
    ),
    "IXR": FutureSymbol(
        symbol="IXR",
        exchange="CME",
        name="CONSUMER STAPLES SELECT SECTOR INDEX",
        tradingClass="XAP",
        currency="USD",
        hasOptions=False,
    ),
    "SIXRE": FutureSymbol(
        symbol="SIXRE",
        exchange="CME",
        name="REAL ESTATE SELECT SECTOR INDEX",
        tradingClass="XAR",
        currency="USD",
        hasOptions=False,
    ),
    "IXU": FutureSymbol(
        symbol="IXU",
        exchange="CME",
        name="UTILITIES SELECT SECTOR INDEX",
        tradingClass="XAU",
        currency="USD",
        hasOptions=False,
    ),
    "IXV": FutureSymbol(
        symbol="IXV",
        exchange="CME",
        name="HEALTH CARE SELECT SECTOR INDEX",
        tradingClass="XAV",
        currency="USD",
        hasOptions=False,
    ),
    "IXY": FutureSymbol(
        symbol="IXY",
        exchange="CME",
        name="CONSUMER DISCRETIONARY SELECT SECTOR INDEX",
        tradingClass="XAY",
        currency="USD",
        hasOptions=False,
    ),
    "XAZ": FutureSymbol(
        symbol="XAZ",
        exchange="CME",
        name="COMMUNICATION SERVICES SELECT SECTOR INDEX",
        tradingClass="XAZ",
        currency="USD",
        hasOptions=False,
    ),
    "1OZ": FutureSymbol(
        symbol="1OZ",
        exchange="COMEX",
        name="1 OUNCE GOLD FUTURES",
        tradingClass="1OZ",
        currency="USD",
        hasOptions=False,
    ),
    "ALI": FutureSymbol(
        symbol="ALI",
        exchange="COMEX",
        name="ALUMINUM INDEX",
        tradingClass="ALI",
        currency="USD",
        hasOptions=False,
    ),
    "GC": FutureSymbol(
        symbol="GC",
        exchange="COMEX",
        name="GOLD",
        tradingClass="GC",
        currency="USD",
        hasOptions=True,
    ),
    "HG": FutureSymbol(
        symbol="HG",
        exchange="COMEX",
        name="COPPER INDEX",
        tradingClass="HG",
        currency="USD",
        hasOptions=True,
    ),
    "HRC": FutureSymbol(
        symbol="HRC",
        exchange="COMEX",
        name="HOT-ROLLED COIL STEEL INDEX",
        tradingClass="HRC",
        currency="USD",
        hasOptions=False,
    ),
    "MGC": FutureSymbol(
        symbol="MGC",
        exchange="COMEX",
        name="E-MICRO GOLD",
        tradingClass="MGC",
        currency="USD",
        hasOptions=True,
    ),
    "MHG": FutureSymbol(
        symbol="MHG",
        exchange="COMEX",
        name="MICRO COPPER",
        tradingClass="MHG",
        currency="USD",
        hasOptions=False,
    ),
    "QC": FutureSymbol(
        symbol="QC",
        exchange="COMEX",
        name="COMEX MINY COPPER",
        tradingClass="QC",
        currency="USD",
        hasOptions=False,
    ),
    "QI": FutureSymbol(
        symbol="QI",
        exchange="COMEX",
        name="COMEX MINY SILVER",
        tradingClass="QI",
        currency="USD",
        hasOptions=False,
    ),
    "QO": FutureSymbol(
        symbol="QO",
        exchange="COMEX",
        name="COMEX MINY GOLD",
        tradingClass="QO",
        currency="USD",
        hasOptions=False,
    ),
    "SGC": FutureSymbol(
        symbol="SGC",
        exchange="COMEX",
        name="SHANGHAI GOLD EXCHANGE GOLD BENCHMARK PM PRICE INDEX - CNH FUTURES",
        tradingClass="SGC",
        currency="CNH",
        hasOptions=False,
    ),
    "SGUF": FutureSymbol(
        symbol="SGUF",
        exchange="COMEX",
        name="SHANGHAI GOLD EXCHANGE GOLD BENCHMARK PM PRICE INDEX - USD FUTURES",
        tradingClass="SGU",
        currency="USD",
        hasOptions=False,
    ),
    "SI": FutureSymbol(
        symbol="SI",
        exchange="COMEX",
        name="SILVER INDEX",
        tradingClass="SI",
        currency="USD",
        hasOptions=True,
    ),
    "UX": FutureSymbol(
        symbol="UX",
        exchange="COMEX",
        name="URANIUM INDEX",
        tradingClass="UX",
        currency="USD",
        hasOptions=False,
    ),
    "ECF": FutureSymbol(
        symbol="ECF",
        exchange="ENDEX",
        name="ICE ECX EUA FUTURES",
        tradingClass="ECF",
        currency="EUR",
        hasOptions=False,
    ),
    "TFM": FutureSymbol(
        symbol="TFM",
        exchange="ENDEX",
        name="DUTCH TTF NATURAL GAS FUTURES",
        tradingClass="TFM",
        currency="EUR",
        hasOptions=True,
    ),
    "CONF": FutureSymbol(
        symbol="CONF",
        exchange="EUREX",
        name="SWISS FEDERAL LONG-TERM BONDS",
        tradingClass="CONF",
        currency="CHF",
        hasOptions=False,
    ),
    "KS200.EU": FutureSymbol(
        symbol="KS200.EU",
        exchange="EUREX",
        name="KOSPI 200 - EUREX/KRX LINKED PRODUCT",
        tradingClass="FBK2",
        currency="KRW",
        hasOptions=True,
    ),
    "FBON": FutureSymbol(
        symbol="FBON",
        exchange="EUREX",
        name="EURO BONO FUTURES ON LONG-TERM SPANISH GOVERNMENT BONDS",
        tradingClass="FBON",
        currency="EUR",
        hasOptions=False,
    ),
    "BTP": FutureSymbol(
        symbol="BTP",
        exchange="EUREX",
        name="EURO-BTP ITALIAN GOVERNMENT BOND",
        tradingClass="FBTP",
        currency="EUR",
        hasOptions=True,
    ),
    "BTS": FutureSymbol(
        symbol="BTS",
        exchange="EUREX",
        name="SHORT-TERM EURO-BTP ITALIAN GOVERNMENT BOND",
        tradingClass="FBTS",
        currency="EUR",
        hasOptions=False,
    ),
    "DJUBS": FutureSymbol(
        symbol="DJUBS",
        exchange="EUREX",
        name="DOW JONES-UBS COMMODITY INDEX",
        tradingClass="FCCO",
        currency="USD",
        hasOptions=False,
    ),
    "KWY.EU": FutureSymbol(
        symbol="KWY.EU",
        exchange="EUREX",
        name="US DOLLAR IN KOREAN WON - EUREX/KRX LINKED PRODUCT",
        tradingClass="FCUW",
        currency="KRW",
        hasOptions=False,
    ),
    "SD3ED": FutureSymbol(
        symbol="SD3ED",
        exchange="EUREX",
        name="EURO STOXX SELECT DIVIDEND 30 DVP",
        tradingClass="FD3D",
        currency="EUR",
        hasOptions=False,
    ),
    "DAX": FutureSymbol(
        symbol="DAX",
        exchange="EUREX",
        name="DAX 40 INDEX (DEUTSCHE AKTIEN XCHANGE 40)",
        tradingClass="FDAX",
        currency="EUR",
        hasOptions=True,
    ),
    "DDAX": FutureSymbol(
        symbol="DDAX",
        exchange="EUREX",
        name="DIVDAX PRICE INDEX",
        tradingClass="FDIV",
        currency="EUR",
        hasOptions=True,
    ),
    "DDXDIVPT": FutureSymbol(
        symbol="DDXDIVPT",
        exchange="EUREX",
        name="DIVDAX DIVIDEND POINTS INDEX",
        tradingClass="FDVD",
        currency="EUR",
        hasOptions=False,
    ),
    "DBEA": FutureSymbol(
        symbol="DBEA",
        exchange="EUREX",
        name="EURO STOXX BANKS INDEX DIVIDEND FUTURES",
        tradingClass="FEBD",
        currency="EUR",
        hasOptions=False,
    ),
    "DJSD": FutureSymbol(
        symbol="DJSD",
        exchange="EUREX",
        name="EURO STOXX SELECT DIVIDEND 30 INDEX",
        tradingClass="FEDV",
        currency="EUR",
        hasOptions=True,
    ),
    "ESA": FutureSymbol(
        symbol="ESA",
        exchange="EUREX",
        name="EURO STOXX 600 AUTOMOBILE & PARTS",
        tradingClass="FESA",
        currency="EUR",
        hasOptions=True,
    ),
    "SX7E": FutureSymbol(
        symbol="SX7E",
        exchange="EUREX",
        name="EURO STOXX BANKS INDEX",
        tradingClass="FESB",
        currency="EUR",
        hasOptions=True,
    ),
    "SX4E": FutureSymbol(
        symbol="SX4E",
        exchange="EUREX",
        name="EURO STOXX CHEMICALS",
        tradingClass="FESC",
        currency="EUR",
        hasOptions=True,
    ),
    "ESE": FutureSymbol(
        symbol="ESE",
        exchange="EUREX",
        name="EURO STOXX OIL & GAS",
        tradingClass="FESE",
        currency="EUR",
        hasOptions=True,
    ),
    "ESF": FutureSymbol(
        symbol="ESF",
        exchange="EUREX",
        name="EURO STOXX FINANCIAL SERVICES INDEX",
        tradingClass="FESF",
        currency="EUR",
        hasOptions=True,
    ),
    "SXNE": FutureSymbol(
        symbol="SXNE",
        exchange="EUREX",
        name="EURO STOXX INDUSTRIAL GOODS&SERVICES",
        tradingClass="FESG",
        currency="EUR",
        hasOptions=True,
    ),
    "SXDE": FutureSymbol(
        symbol="SXDE",
        exchange="EUREX",
        name="EURO STOXX HEALTHCARE",
        tradingClass="FESH",
        currency="EUR",
        hasOptions=True,
    ),
    "ESI": FutureSymbol(
        symbol="ESI",
        exchange="EUREX",
        name="EURO STOXX INSURANCE",
        tradingClass="FESI",
        currency="EUR",
        hasOptions=True,
    ),
    "ESM": FutureSymbol(
        symbol="ESM",
        exchange="EUREX",
        name="EURO STOXX MEDIA INDEX",
        tradingClass="FESM",
        currency="EUR",
        hasOptions=True,
    ),
    "SXOE": FutureSymbol(
        symbol="SXOE",
        exchange="EUREX",
        name="EURO STOXX CONSTRUCTION",
        tradingClass="FESN",
        currency="EUR",
        hasOptions=True,
    ),
    "SX3E": FutureSymbol(
        symbol="SX3E",
        exchange="EUREX",
        name="EURO STOXX FOOD&BEVERAGES",
        tradingClass="FESO",
        currency="EUR",
        hasOptions=True,
    ),
    "SXRE": FutureSymbol(
        symbol="SXRE",
        exchange="EUREX",
        name="EURO STOXX RETAIL",
        tradingClass="FESR",
        currency="EUR",
        hasOptions=True,
    ),
    "SXPE": FutureSymbol(
        symbol="SXPE",
        exchange="EUREX",
        name="EURO STOXX BASIC RESOURCES",
        tradingClass="FESS",
        currency="EUR",
        hasOptions=True,
    ),
    "SXKE": FutureSymbol(
        symbol="SXKE",
        exchange="EUREX",
        name="EURO STOXX TELECOMMUNICATIONS",
        tradingClass="FEST",
        currency="EUR",
        hasOptions=True,
    ),
    "ESU": FutureSymbol(
        symbol="ESU",
        exchange="EUREX",
        name="EURO STOXX UTILITIES INDEX",
        tradingClass="FESU",
        currency="EUR",
        hasOptions=True,
    ),
    "SXTE": FutureSymbol(
        symbol="SXTE",
        exchange="EUREX",
        name="EURO STOXX TRAVEL & LEISURE",
        tradingClass="FESV",
        currency="EUR",
        hasOptions=True,
    ),
    "ESTX50": FutureSymbol(
        symbol="ESTX50",
        exchange="EUREX",
        name="EURO STOXX50",
        tradingClass="FESX",
        currency="EUR",
        hasOptions=True,
    ),
    "SX8E": FutureSymbol(
        symbol="SX8E",
        exchange="EUREX",
        name="EURO STOXX TECHNOLOGY",
        tradingClass="FESY",
        currency="EUR",
        hasOptions=True,
    ),
    "SXQE": FutureSymbol(
        symbol="SXQE",
        exchange="EUREX",
        name="EURO STOXX PERSONAL & HOUSEHOLD GOODS",
        tradingClass="FESZ",
        currency="EUR",
        hasOptions=True,
    ),
    "EU3": FutureSymbol(
        symbol="EU3",
        exchange="EUREX",
        name="THREE MONTH EURIBOR",
        tradingClass="FEU3",
        currency="EUR",
        hasOptions=True,
    ),
    "DESX5": FutureSymbol(
        symbol="DESX5",
        exchange="EUREX",
        name="EURO STOXX 50 INDEX-DIVIDENDEN",
        tradingClass="FEXD",
        currency="EUR",
        hasOptions=True,
    ),
    "OMXH25": FutureSymbol(
        symbol="OMXH25",
        exchange="EUREX",
        name="OMX HELSINKI 25 INDEX",
        tradingClass="FFOX",
        currency="EUR",
        hasOptions=True,
    ),
    "GBL": FutureSymbol(
        symbol="GBL",
        exchange="EUREX",
        name="EURO BUND (10 YEAR BOND)",
        tradingClass="FGBL",
        currency="EUR",
        hasOptions=True,
    ),
    "GBM": FutureSymbol(
        symbol="GBM",
        exchange="EUREX",
        name="EURO BOBL (5 YEAR BOND)",
        tradingClass="FGBM",
        currency="EUR",
        hasOptions=True,
    ),
    "GBS": FutureSymbol(
        symbol="GBS",
        exchange="EUREX",
        name="EURO SCHATZ (2 YEAR BOND)",
        tradingClass="FGBS",
        currency="EUR",
        hasOptions=True,
    ),
    "GBX": FutureSymbol(
        symbol="GBX",
        exchange="EUREX",
        name="EURO BUXL (15 - 30 YEAR BOND)",
        tradingClass="FGBX",
        currency="EUR",
        hasOptions=True,
    ),
    "DJESL": FutureSymbol(
        symbol="DJESL",
        exchange="EUREX",
        name="EURO STOXX LARGE",
        tradingClass="FLCE",
        currency="EUR",
        hasOptions=False,
    ),
    "DJ200L": FutureSymbol(
        symbol="DJ200L",
        exchange="EUREX",
        name="STOXX LARGE 200 INDEX",
        tradingClass="FLCP",
        currency="EUR",
        hasOptions=False,
    ),
    "DJESM": FutureSymbol(
        symbol="DJESM",
        exchange="EUREX",
        name="EURO STOXX MID",
        tradingClass="FMCE",
        currency="EUR",
        hasOptions=False,
    ),
    "M1CN": FutureSymbol(
        symbol="M1CN",
        exchange="EUREX",
        name="MSCI CHINA NTR USD",
        tradingClass="FMCH",
        currency="USD",
        hasOptions=False,
    ),
    "DJ200": FutureSymbol(
        symbol="DJ200",
        exchange="EUREX",
        name="STOXX MID 200 INDEX",
        tradingClass="FMCP",
        currency="EUR",
        hasOptions=True,
    ),
    "M1MS": FutureSymbol(
        symbol="M1MS",
        exchange="EUREX",
        name="MSCI EMERGING MARKETS ASIA",
        tradingClass="FMEA",
        currency="USD",
        hasOptions=False,
    ),
    "M1EF": FutureSymbol(
        symbol="M1EF",
        exchange="EUREX",
        name="MSCI EMERGING MARKETS NET TOTAL RETURN INDEX",
        tradingClass="FMEM",
        currency="USD",
        hasOptions=False,
    ),
    "MXEU": FutureSymbol(
        symbol="MXEU",
        exchange="EUREX",
        name="MSCI EUROPE",
        tradingClass="FMEP",
        currency="EUR",
        hasOptions=False,
    ),
    "M7EU": FutureSymbol(
        symbol="M7EU",
        exchange="EUREX",
        name="MSCI EUROPE NET RETURN EUR INDEX",
        tradingClass="FMEU",
        currency="EUR",
        hasOptions=False,
    ),
    "M1IN": FutureSymbol(
        symbol="M1IN",
        exchange="EUREX",
        name="MSCI INDIA NTR USD",
        tradingClass="FMIN",
        currency="USD",
        hasOptions=False,
    ),
    "MXJPUS": FutureSymbol(
        symbol="MXJPUS",
        exchange="EUREX",
        name="MSCI JAPAN INDEX - USD",
        tradingClass="FMJP",
        currency="USD",
        hasOptions=False,
    ),
    "K200M.EU": FutureSymbol(
        symbol="K200M.EU",
        exchange="EUREX",
        name="MINI KOSPI 200 - EUREX/KRX LINKED PRODUCT",
        tradingClass="FMK2",
        currency="KRW",
        hasOptions=False,
    ),
    "M1TW": FutureSymbol(
        symbol="M1TW",
        exchange="EUREX",
        name="MSCI TAIWAN NTR USD",
        tradingClass="FMTW",
        currency="USD",
        hasOptions=False,
    ),
    "MBWO": FutureSymbol(
        symbol="MBWO",
        exchange="EUREX",
        name="MSCI WORLD NET EUR INDEX 1",
        tradingClass="FMWN",
        currency="EUR",
        hasOptions=False,
    ),
    "M1WO": FutureSymbol(
        symbol="M1WO",
        exchange="EUREX",
        name="MSCI WORLD NETR USD INDEX",
        tradingClass="FMWO",
        currency="USD",
        hasOptions=False,
    ),
    "MXWO": FutureSymbol(
        symbol="MXWO",
        exchange="EUREX",
        name="MSCI WORLD INDEX",
        tradingClass="FMWP",
        currency="USD",
        hasOptions=False,
    ),
    "OAT": FutureSymbol(
        symbol="OAT",
        exchange="EUREX",
        name="EURO-OAT FRENCH GOVERNMENT BOND",
        tradingClass="FOAT",
        currency="EUR",
        hasOptions=False,
    ),
    "DJESS": FutureSymbol(
        symbol="DJESS",
        exchange="EUREX",
        name="EURO STOXX SMALL",
        tradingClass="FSCE",
        currency="EUR",
        hasOptions=False,
    ),
    "DJ200S": FutureSymbol(
        symbol="DJ200S",
        exchange="EUREX",
        name="STOXX SMALL 200 INDEX",
        tradingClass="FSCP",
        currency="EUR",
        hasOptions=False,
    ),
    "SXXPESGX": FutureSymbol(
        symbol="SXXPESGX",
        exchange="EUREX",
        name="STOXX EUROPE 600 ESG-X",
        tradingClass="FSEG",
        currency="EUR",
        hasOptions=False,
    ),
    "SLI": FutureSymbol(
        symbol="SLI",
        exchange="EUREX",
        name="SWISS LEADER INDEX (PREIS_INDEX)",
        tradingClass="FSLI",
        currency="CHF",
        hasOptions=True,
    ),
    "SMIDP": FutureSymbol(
        symbol="SMIDP",
        exchange="EUREX",
        name="SMI DIVIDEND POINTS INDEX",
        tradingClass="FSMD",
        currency="CHF",
        hasOptions=False,
    ),
    "SMI": FutureSymbol(
        symbol="SMI",
        exchange="EUREX",
        name="SWISS MARKET INDEX",
        tradingClass="FSMI",
        currency="CHF",
        hasOptions=True,
    ),
    "SMIM": FutureSymbol(
        symbol="SMIM",
        exchange="EUREX",
        name="SWISS MID-CAP INDEX",
        tradingClass="FSMM",
        currency="CHF",
        hasOptions=True,
    ),
    "MDAX": FutureSymbol(
        symbol="MDAX",
        exchange="EUREX",
        name="MIDCAP DAX",
        tradingClass="FSMX",
        currency="EUR",
        hasOptions=False,
    ),
    "ST3": FutureSymbol(
        symbol="ST3",
        exchange="EUREX",
        name="THREE MONTH ESTR",
        tradingClass="FST3",
        currency="EUR",
        hasOptions=False,
    ),
    "SXAP": FutureSymbol(
        symbol="SXAP",
        exchange="EUREX",
        name="STOXX 600 AUTOMOBILES & PARTS",
        tradingClass="FSTA",
        currency="EUR",
        hasOptions=True,
    ),
    "SX7P": FutureSymbol(
        symbol="SX7P",
        exchange="EUREX",
        name="STOXX 600 BANKS",
        tradingClass="FSTB",
        currency="EUR",
        hasOptions=True,
    ),
    "SX4P": FutureSymbol(
        symbol="SX4P",
        exchange="EUREX",
        name="STOXX 600 CHEMICALS",
        tradingClass="FSTC",
        currency="EUR",
        hasOptions=True,
    ),
    "SXEP": FutureSymbol(
        symbol="SXEP",
        exchange="EUREX",
        name="STOXX 600 OIL & GAS",
        tradingClass="FSTE",
        currency="EUR",
        hasOptions=True,
    ),
    "SXFP": FutureSymbol(
        symbol="SXFP",
        exchange="EUREX",
        name="STOXX 600 FINANCIAL SERVICES INDEX",
        tradingClass="FSTF",
        currency="EUR",
        hasOptions=True,
    ),
    "SXNP": FutureSymbol(
        symbol="SXNP",
        exchange="EUREX",
        name="STOXX 600 INDUSTRIAL GOODS & SERVICES INDEX",
        tradingClass="FSTG",
        currency="EUR",
        hasOptions=True,
    ),
    "SXDP": FutureSymbol(
        symbol="SXDP",
        exchange="EUREX",
        name="STOXX 600 HEALTHCARE",
        tradingClass="FSTH",
        currency="EUR",
        hasOptions=True,
    ),
    "SXIP": FutureSymbol(
        symbol="SXIP",
        exchange="EUREX",
        name="STOXX 600 INSURANCE",
        tradingClass="FSTI",
        currency="EUR",
        hasOptions=True,
    ),
    "SX86P": FutureSymbol(
        symbol="SX86P",
        exchange="EUREX",
        name="STOXX 600 REAL ESTATE",
        tradingClass="FSTL",
        currency="EUR",
        hasOptions=False,
    ),
    "SXMP": FutureSymbol(
        symbol="SXMP",
        exchange="EUREX",
        name="STOXX 600 MEDIA",
        tradingClass="FSTM",
        currency="EUR",
        hasOptions=True,
    ),
    "SXOP": FutureSymbol(
        symbol="SXOP",
        exchange="EUREX",
        name="STOXX 600 CONSTRUCTION & MATERIALS",
        tradingClass="FSTN",
        currency="EUR",
        hasOptions=True,
    ),
    "SX3P": FutureSymbol(
        symbol="SX3P",
        exchange="EUREX",
        name="STOXX 600 FOOD & BEVERAGE INDEX",
        tradingClass="FSTO",
        currency="EUR",
        hasOptions=True,
    ),
    "SXRP": FutureSymbol(
        symbol="SXRP",
        exchange="EUREX",
        name="STOXX 600 RETAIL",
        tradingClass="FSTR",
        currency="EUR",
        hasOptions=True,
    ),
    "SXPP": FutureSymbol(
        symbol="SXPP",
        exchange="EUREX",
        name="STOXX 600 BASIC RESOURCES INDEX",
        tradingClass="FSTS",
        currency="EUR",
        hasOptions=True,
    ),
    "SXKP": FutureSymbol(
        symbol="SXKP",
        exchange="EUREX",
        name="STOXX 600 TELECOMMUNICATIONS",
        tradingClass="FSTT",
        currency="EUR",
        hasOptions=True,
    ),
    "SX6P": FutureSymbol(
        symbol="SX6P",
        exchange="EUREX",
        name="STOXX 600 UTILITIES",
        tradingClass="FSTU",
        currency="EUR",
        hasOptions=True,
    ),
    "SXTP": FutureSymbol(
        symbol="SXTP",
        exchange="EUREX",
        name="STOXX 600 TRAVEL & LEISURE",
        tradingClass="FSTV",
        currency="EUR",
        hasOptions=True,
    ),
    "STX": FutureSymbol(
        symbol="STX",
        exchange="EUREX",
        name="STOXX50",
        tradingClass="FSTX",
        currency="EUR",
        hasOptions=True,
    ),
    "SX8P": FutureSymbol(
        symbol="SX8P",
        exchange="EUREX",
        name="STOXX 600 TECHNOLOGY",
        tradingClass="FSTY",
        currency="EUR",
        hasOptions=True,
    ),
    "SXQP": FutureSymbol(
        symbol="SXQP",
        exchange="EUREX",
        name="STOXX 600 PERSONAL & HOUSEHOLD GOODS",
        tradingClass="FSTZ",
        currency="EUR",
        hasOptions=True,
    ),
    "TDX": FutureSymbol(
        symbol="TDX",
        exchange="EUREX",
        name="TECDAX",
        tradingClass="FTDX",
        currency="EUR",
        hasOptions=True,
    ),
    "V2TX": FutureSymbol(
        symbol="V2TX",
        exchange="EUREX",
        name="VSTOXX VOLATILITY INDEX",
        tradingClass="FVS",
        currency="EUR",
        hasOptions=True,
    ),
    "DJES": FutureSymbol(
        symbol="DJES",
        exchange="EUREX",
        name="EURO STOXX PRICE INDEX",
        tradingClass="FXXE",
        currency="EUR",
        hasOptions=False,
    ),
    "DJ600": FutureSymbol(
        symbol="DJ600",
        exchange="EUREX",
        name="STOXX 600 INDEX",
        tradingClass="FXXP",
        currency="EUR",
        hasOptions=True,
    ),
    "EJ": FutureSymbol(
        symbol="EJ",
        exchange="ICEUS",
        name="NYBOT EURO IN JAPANESE YEN",
        tradingClass="KEJ",
        currency="JPY",
        hasOptions=False,
    ),
    "EO": FutureSymbol(
        symbol="EO",
        exchange="ICEUS",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="KEO",
        currency="USD",
        hasOptions=False,
    ),
    "GB": FutureSymbol(
        symbol="GB",
        exchange="ICEUS",
        name="EUROPEAN MONETARY UNION EURO",
        tradingClass="KGB",
        currency="GBP",
        hasOptions=False,
    ),
    "RZ": FutureSymbol(
        symbol="RZ",
        exchange="ICEUS",
        name="NYBOT EURO IN SWISS FRANC",
        tradingClass="KRZ",
        currency="CHF",
        hasOptions=False,
    ),
    "ZY": FutureSymbol(
        symbol="ZY",
        exchange="ICEUS",
        name="SWISS FRANC",
        tradingClass="KZY",
        currency="JPY",
        hasOptions=False,
    ),
    "MP": FutureSymbol(
        symbol="MP",
        exchange="ICEUS",
        name="BRITISH POUND",
        tradingClass="MP",
        currency="USD",
        hasOptions=False,
    ),
    "SS": FutureSymbol(
        symbol="SS",
        exchange="ICEUS",
        name="BRITISH POUND IN SWISS FRANC",
        tradingClass="SS",
        currency="CHF",
        hasOptions=False,
    ),
    "SY": FutureSymbol(
        symbol="SY",
        exchange="ICEUS",
        name="JAPANESE YEN",
        tradingClass="SY",
        currency="JPY",
        hasOptions=False,
    ),
    "LRC30APR": FutureSymbol(
        symbol="LRC30APR",
        exchange="NYBOT",
        name="ICE U.S. CONFORMING 30-YR FIXED MORTGAGE RATE LOCK WEIGHTED APR",
        tradingClass="30C",
        currency="USD",
        hasOptions=False,
    ),
    "CC": FutureSymbol(
        symbol="CC",
        exchange="NYBOT",
        name="COCOA NYBOT",
        tradingClass="CC",
        currency="USD",
        hasOptions=True,
    ),
    "CT": FutureSymbol(
        symbol="CT",
        exchange="NYBOT",
        name="COTTON NO. 2",
        tradingClass="CT",
        currency="USD",
        hasOptions=True,
    ),
    "DX": FutureSymbol(
        symbol="DX",
        exchange="NYBOT",
        name="NYBOT US DOLLAR FX",
        tradingClass="DX",
        currency="USD",
        hasOptions=True,
    ),
    "NYFANG": FutureSymbol(
        symbol="NYFANG",
        exchange="NYBOT",
        name="NYSE FANG+ INDEX",
        tradingClass="FNG",
        currency="USD",
        hasOptions=False,
    ),
    "KC": FutureSymbol(
        symbol="KC",
        exchange="NYBOT",
        name='COFFEE "C"',
        tradingClass="KC",
        currency="USD",
        hasOptions=True,
    ),
    "OJ": FutureSymbol(
        symbol="OJ",
        exchange="NYBOT",
        name='FC ORANGE JUICE "A"',
        tradingClass="OJ",
        currency="USD",
        hasOptions=True,
    ),
    "RS": FutureSymbol(
        symbol="RS",
        exchange="NYBOT",
        name="CANOLA",
        tradingClass="RS",
        currency="CAD",
        hasOptions=False,
    ),
    "SB": FutureSymbol(
        symbol="SB",
        exchange="NYBOT",
        name="SUGAR NO. 11",
        tradingClass="SB",
        currency="USD",
        hasOptions=True,
    ),
    "SF": FutureSymbol(
        symbol="SF",
        exchange="NYBOT",
        name="SUGAR #16 112000 LBS",
        tradingClass="SF",
        currency="USD",
        hasOptions=False,
    ),
    "BB": FutureSymbol(
        symbol="BB",
        exchange="NYMEX",
        name="NYMEX BRENT FINANCIAL FUTURES INDEX",
        tradingClass="BB",
        currency="USD",
        hasOptions=False,
    ),
    "BZ": FutureSymbol(
        symbol="BZ",
        exchange="NYMEX",
        name="BRENT CRUDE OIL - LAST DAY",
        tradingClass="BZ",
        currency="USD",
        hasOptions=True,
    ),
    "CL": FutureSymbol(
        symbol="CL",
        exchange="NYMEX",
        name="LIGHT SWEET CRUDE OIL",
        tradingClass="CL",
        currency="USD",
        hasOptions=True,
    ),
    "HH": FutureSymbol(
        symbol="HH",
        exchange="NYMEX",
        name="NATURAL GAS LAST DAY FINANCIAL FUTURES INDEX",
        tradingClass="HH",
        currency="USD",
        hasOptions=False,
    ),
    "HHW": FutureSymbol(
        symbol="HHW",
        exchange="NYMEX",
        name="HENRY HUB NATURAL GAS (WEEKLY FUTURES)",
        tradingClass="HHW",
        currency="USD",
        hasOptions=False,
    ),
    "HO": FutureSymbol(
        symbol="HO",
        exchange="NYMEX",
        name="HEATING OIL",
        tradingClass="HO",
        currency="USD",
        hasOptions=True,
    ),
    "HP": FutureSymbol(
        symbol="HP",
        exchange="NYMEX",
        name="NATURAL GAS PENULTIMATE FINANCIAL FUTURES INDEX",
        tradingClass="HP",
        currency="USD",
        hasOptions=False,
    ),
    "MCL": FutureSymbol(
        symbol="MCL",
        exchange="NYMEX",
        name="MICRO WTI CRUDE OIL",
        tradingClass="MCL",
        currency="USD",
        hasOptions=True,
    ),
    "MHO": FutureSymbol(
        symbol="MHO",
        exchange="NYMEX",
        name="MICRO NY HARBOR ULSD",
        tradingClass="MHO",
        currency="USD",
        hasOptions=False,
    ),
    "MHNG": FutureSymbol(
        symbol="MHNG",
        exchange="NYMEX",
        name="MICRO HENRY HUB NATURAL GAS",
        tradingClass="MNG",
        currency="USD",
        hasOptions=False,
    ),
    "MRB": FutureSymbol(
        symbol="MRB",
        exchange="NYMEX",
        name="MICRO RBOB GASOLINE",
        tradingClass="MRB",
        currency="USD",
        hasOptions=False,
    ),
    "NG": FutureSymbol(
        symbol="NG",
        exchange="NYMEX",
        name="HENRY HUB NATURAL GAS",
        tradingClass="NG",
        currency="USD",
        hasOptions=True,
    ),
    "PA": FutureSymbol(
        symbol="PA",
        exchange="NYMEX",
        name="PALLADIUM INDEX",
        tradingClass="PA",
        currency="USD",
        hasOptions=False,
    ),
    "PL": FutureSymbol(
        symbol="PL",
        exchange="NYMEX",
        name="PLATINUM INDEX",
        tradingClass="PL",
        currency="USD",
        hasOptions=False,
    ),
    "QG": FutureSymbol(
        symbol="QG",
        exchange="NYMEX",
        name="NYMEX MINY NATURAL GAS INDEX",
        tradingClass="QG",
        currency="USD",
        hasOptions=False,
    ),
    "QM": FutureSymbol(
        symbol="QM",
        exchange="NYMEX",
        name="NYMEX MINY LIGHT SWEET CRUDE OIL",
        tradingClass="QM",
        currency="USD",
        hasOptions=False,
    ),
    "RB": FutureSymbol(
        symbol="RB",
        exchange="NYMEX",
        name="NYMEX RBOB GASOLINE INDEX",
        tradingClass="RB",
        currency="USD",
        hasOptions=True,
    ),
    "TT": FutureSymbol(
        symbol="TT",
        exchange="NYMEX",
        name="NYMEX COTTON INDEX",
        tradingClass="TT",
        currency="USD",
        hasOptions=False,
    ),
    "M1MSA": FutureSymbol(
        symbol="M1MSA",
        exchange="NYSELIFFE",
        name="MSCI EMERGING MARKETS ASIA NET TOTAL RETURN (NTR)",
        tradingClass="ASN",
        currency="USD",
        hasOptions=False,
    ),
    "M1EU": FutureSymbol(
        symbol="M1EU",
        exchange="NYSELIFFE",
        name="MSCI EUROPE NTR",
        tradingClass="EU9",
        currency="USD",
        hasOptions=False,
    ),
    "M1JP": FutureSymbol(
        symbol="M1JP",
        exchange="NYSELIFFE",
        name="THE MSCI JAPAN NTR",
        tradingClass="JPP",
        currency="USD",
        hasOptions=False,
    ),
    "MXEA": FutureSymbol(
        symbol="MXEA",
        exchange="NYSELIFFE",
        name="MSCI EAFE INDEX",
        tradingClass="MFS",
        currency="USD",
        hasOptions=False,
    ),
    "MXEF": FutureSymbol(
        symbol="MXEF",
        exchange="NYSELIFFE",
        name="MSCI EMERGING MARKETS INDEX",
        tradingClass="MME",
        currency="USD",
        hasOptions=False,
    ),
    "MXUS": FutureSymbol(
        symbol="MXUS",
        exchange="NYSELIFFE",
        name="MSCI USA INDEX",
        tradingClass="MUN",
        currency="USD",
        hasOptions=False,
    ),
} | {
    # also bring in new "event contracts" which are CME futures products with daily expirations
    # https://www.cmegroup.com/activetrader/event-contracts/contract-specifications-for-event-contracts.html
    # there is also https://forecastex.com/markets/
    # Even though we have "symbols" for these, I haven't found a way to actually add quotes or qualify contracts for them.
    # It appears currently the only way to use the forecast contracts is at https://forecasttrader.interactivebrokers.com/
    sym: FutureSymbol(
        symbol=sym,
        exchange="CME",
        name=sym,
        currency="USD",
        hasOptions=False,
        tradingClass=sym,
    )
    for sym in "ECBTC ECCL ECNG ECES ECNQ ECRTY ECYM EC6E ECGC ECSI ECHG".split()
}

# === 4. addTradingClassToTopLevel — auto-index by tradingClass ==============


def addTradingClassToTopLevel():
    fuadd = {}
    for name, sym in FUTS_EXCHANGE.items():
        # Populating trading class as a top-level lookup symbol if it doesn't match the IBKR symbol name
        # e.g. /SDA is /SPXDIVAN on IBKR and it doesn't work right etc.
        if sym.tradingClass != name:
            fuadd[sym.tradingClass] = sym

    fk = fuadd.keys()
    fek = FUTS_EXCHANGE.keys()

    both = fk & fek
    assert (
        not both
    ), f"Trading Class and Futures Symbols have conflicting names: {', '.join(both)}"

    return fuadd


FUTS_EXCHANGE |= addTradingClassToTopLevel()

